default_install_hook_types:
  - pre-push
default_stages:
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with cargo fmt.
        entry: cargo +nightly fmt --
        language: system
        files: \.rs$
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: cargo clippy -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
