[package]
name = "flichess"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
debug = true

[dependencies]
arrayvec = "0.7.4"
bitflags = "2.6.0"
clap = { version = "4.5.15", features = ["derive"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rustyline = "14.0.0"
