[package]
name = "pounce"
authors = ["alex flick"]
edition = "2024"
version = "3.0.0"
build = "build.rs"
default-run = "pounce"
repository = "https://github.com/0xflick/pounce"
description = "A mediocre (but trying its best) uci chess engine"
readme = "README.md"
license = "MIT"
keywords = ["chess", "uci", "engine"]
categories = ["games"]

[[bin]]
name = "datagen"
path = "src/bin/datagen.rs"
required-features = ["datagen"]

[[bin]]
name = "wiz"
path = "src/bin/wiz/main.rs"
required-features = ["wiz"]

[features]
datagen = [
  "clap",
  "ctrlc",
  "serde",
  "serde_json",
  "rand/os_rng",
  "rand/std_rng",
]
wiz = ["clap"]

[dependencies]
anyhow = "1.0.86"
arrayvec = "0.7.4"
bitflags = "2.6.0"
clap = { version = "4.5.15", features = ["derive"], optional = true }
ctrlc = { version = "3.4.5", features = ["termination"], optional = true }
rand = { version = "0.9.3", default-features = false, features = ["small_rng", "std"] }
serde = { version = "1.0.209", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
thiserror = "2.0.11"

[dev-dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }

[[bench]]
name = "search_bench"
harness = false

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 1
lto = true
panic = "abort"

[profile.profile]
inherits = "release"
debug = true
